from app.repositories.base_repo import BaseRepository
from app.repositories.employee_repo import EmployeeRepository
from app.repositories.attendance_repo import AttendanceRepository
from app.repositories.department_repo import DepartmentRepository
from app.repositories.leave_repo import LeaveRepository
from app.repositories.task_repo import TaskRepository
from app.repositories.recruitment_repo import RecruitmentRepository
from app.repositories.analytics_repo import AnalyticsRepository
from app.repositories.ai_repo import AIRepository
from app.repositories.unit_of_work import UnitOfWork
